services:
  - type: web
    name: danish-systems-3-bots-controller
    env: python
    plan: free
    buildCommand: pip install -r controller/requirements.in
    startCommand: uvicorn controller.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DANISH_CMD
        value: python bot.py
      - key: ENCRYPTION_CMD
        value: python main.py
      - key: MAIGRET_CMD
        value: pnpm start
